In [45]:
import numpy as np

a1 = np.array([2, 4, 5, 3, 1, 8, 6, 1, 9, 12])
print(a1)

[ 2  4  5  3  1  8  6  1  9 12]


In [46]:
a2 = np.array(
            [[2, 3, 1, 9],
            [3, 1, 5, 4],
            [4, 7, 8, 5]
            ])

print(a2)

[[2 3 1 9]
 [3 1 5 4]
 [4 7 8 5]]


In [47]:
a2[1][2]

5

type of array - 2d

In [48]:
a2.ndim

2

3 rows, 4 columns

In [49]:
a2.shape

(3, 4)

In [50]:
a2.size

12

In [51]:
a2.dtype

dtype('int64')

In [52]:
a2.itemsize

8

In [53]:
a2.nbytes

96

In [54]:
a2[2][3] = 100

print(a2)

[[  2   3   1   9]
 [  3   1   5   4]
 [  4   7   8 100]]
