In [33]:
import numpy as np

a = np.array([2, 4, 5, 3, 1, 8, 6, 1, 9, 12])
b = np.array(
            [[2, 3, 1, 9],
            [3, 1, 5, 4],
            [4, 7, 8, 5]
            ])

print(a)
print(b)

[ 2  4  5  3  1  8  6  1  9 12]
[[2 3 1 9]
 [3 1 5 4]
 [4 7 8 5]]


simple arithmetic + *  / ...

In [34]:
a = a + 1
print(a)

[ 3  5  6  4  2  9  7  2 10 13]


In [35]:
b = b * 2 
print(b)

[[ 4  6  2 18]
 [ 6  2 10  8]
 [ 8 14 16 10]]


arithmetic on specific item

In [36]:
a[1] *= 2
print(a)

[ 3 10  6  4  2  9  7  2 10 13]


In [37]:
b[1][2] *= 200
print(b)

[[   4    6    2   18]
 [   6    2 2000    8]
 [   8   14   16   10]]


In [38]:
print(a[:4])

[ 3 10  6  4]


pehle row then column in 2d

In [39]:
print(b[:2, :3])

[[   4    6    2]
 [   6    2 2000]]


In [40]:
print(b[:1, :])

[[ 4  6  2 18]]


In [41]:
print(b[:, :1])

[[4]
 [6]
 [8]]


only integer will be considered

In [42]:
c = np.array([2, 4, 5.9, 3, 1, 8.4, 6, 1, 9, 12], dtype=int)
print(c)

[ 2  4  5  3  1  8  6  1  9 12]
