In [33]:
import numpy as np

a = np.linspace(0, 2, 9)
print(a)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


Trignometry - sin, cos, tan

In [34]:
print(np.sin(a))

[0.         0.24740396 0.47942554 0.68163876 0.84147098 0.94898462
 0.99749499 0.98398595 0.90929743]


simple additions

In [35]:
b = np.array([-1, -2, 5, 4])
c = np.array([1, 3, 7, 6])

print(np.add(b, c))

[ 0  1 12 10]


In [36]:
print(b)

[-1 -2  5  4]


modulus values

In [37]:
print(abs(b))

[1 2 5 4]


In [38]:
print(pow(b, 2))

[ 1  4 25 16]


In [39]:
print(np.log10(c))

[0.         0.47712125 0.84509804 0.77815125]


Maximum num

In [40]:
print(np.max(c))

7


location of max

In [41]:
print(np.argmax(c))

2


In [42]:
print(np.sqrt(c))

[1.         1.73205081 2.64575131 2.44948974]


In [43]:
print(np.append(c, [100, 200, 300]))

[  1   3   7   6 100 200 300]


random integers

In [44]:
big_data = np.random.random_integers(1, 15, 25)
print(big_data)

[14 15  7  7 15  4 11 12 15  4 14 15  6 11  5 13  4  9  8 15  9  1  9  4
 10]


/tmp/ipykernel_5064/3757664732.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 15 + 1) instead
  big_data = np.random.random_integers(1, 15, 25)
