In [45]:
import numpy as np

a = np.zeros([3, 4], dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [46]:
a = np.ones([3, 4], dtype=float)
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [47]:
a = np.ones([3, 4], dtype=str)
print(a)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


sequence create

In [48]:
b = np.arange(5, 70, 4)
print(b)

[ 5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69]


In [49]:
b = np.linspace(3, 7, 9)
print(b)
b

[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7. ]


array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ])

1D to 2D

In [50]:
a = np.array([1, 9, 4, 6, 2, 7])
b = np.reshape(a, (2, 3))
print(b)

[[1 9 4]
 [6 2 7]]


In [51]:
c = np.arange(1, 9, 1)
print(c)

[1 2 3 4 5 6 7 8]


In [52]:
d = np.concatenate([a, c])
print(d)

[1 9 4 6 2 7 1 2 3 4 5 6 7 8]
